services:
  - type: web
    name: bitespeed-app
    runtime: docker
    dockerfilePath: Dockerfile
    env: docker
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: bitespeed-db
          property: connectionString
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        fromDatabase:
          name: bitespeed-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: bitespeed-db
          property: password
      - key: DB_NAME
        value: bitespeed
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    plan: free

  - type: postgres
    name: bitespeed-db
    plan: free
    databaseName: bitespeed
    user: postgres